name: Python CI

#trigger the workflow on push or pull request events but only for the main branch
on:
  push:
    branches: 
        - main
  pull_request:
    branches: 
        - main

# Define the jobs that will run in this workflow
jobs:
  build:
    runs-on: ubuntu-latest
    #Steps are the individual tasks that will be run as part of the job
    steps:
        #Step1: Checkout the code from the repository
        - name: Checkout code
          uses: actions/checkout@v4
        
          #Step2: Set up Python enbvironment
        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"
    
        #Step3: Install dependencies and run tests
        - name: Install dependencies
          run: 
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        #Step4: Run tests
        - name: Run tests
          run: pytest
